### ISSUE TITLE
Prefix/ Suffix

### ISSUE THREAD

**Issue by ghost** [ELCHILEN0/AutoMessage#19]
Hello, prefixes and suffixes don't work. If I for example copy the sample config from here: http://dev.bukkit.org/bukkit-plugins/automessage/pages/configuration-guide/ and reload or restart the server, it just removes the two lines of prefix and suffix.

AutoMessages 2.5.1
spigot #1517

**Comment by TNTUP** [comment]
That'S why I kept AutoMessage 2.3.5 forever... since now 1.12-pre2 broke it, idk since when prefixes got removed... now my automessages looks weird! :/ 

Before (Better) / After (Worse) https://i.qcfb.ca/201705172057530.png I'll try the last good version that works in 1.12... (also sorry for necroposting this 3 year old issue.

EDIT: No good versions has the prefixes/suffixes, they get removed. Any idea to see Prefix/Suffix to be readded? I cannot move to 1.12, staying on 1.11.2 forever until it gets unsupported
